### PR TITLE
Consolidation of bugs/Features & Redux implementation

### LINKED ISSUE #147: Switch case disappear after pressing on a building
**Label Issue**

The switch case only exists in the bottom menu when the user does not click on any building/class. There is no way to get it back after that. 

**Path to fix this are:**

- When you click on the map, the selection is removed and the bottom menu gets back to the view with the switch

### LINKED ISSUE #149: Add X button to remove the selected building in the bottom menu

### LINKED ISSUE #221: Fix Disconnection to dev app [memory leak]
## Issue
From time to time, we receive a too many pending callbacks in the console and it disconnects the tunnel from the app. There are two scenarios in which this warning is thrown and breaks the dev flow.
1. When you go in a context not in the app (For instance, in Google Calendar, when trying to connect, this happens almost 90% of the time. 
2. When you have been testing the app in your device for too long.
## Screenshot
image

## Why is this important
As the warning suggests, we might have a memory leak in our app so this warning should be eliminated to avoid our app to really crash when release.

### LINKED ISSUE #227: Update Map upon selecting item in Search Bar.
When the user selects an item in the searchBar from the home page, the map should update its region as well as displaying a marker. 
1. If the value is a highlighted building, it should be highlighted.
2. Upon clicking on the map, the map is reset to initial view.

### PR DESCRIPTION
**Pull request by AlainJobs**
## Overview
This Pull Request was, in the beginning, focused on finding a solution for when the app kept being disconnected due to a memory leak caused by infinite intervals of AsyncStorage calls. This led me to make some more research into what could be done. The goal was also to avoid Redux since it could take a while. However, while attempting to use Redux, I made it work, thus I thought it could be a nice addition. It made the app quite faster even with the number of new components/screens added.
**Disclaimer:**  I didn't touch anything in the indoor components & SideMenu. 
There are still some warning this and there (not supposded to have in the files I've changed.)

### Map is updated when clicking an item + marker in **searchBar**
ezgif com-optimize

### Polygons color and stroke width are added and dynamic + unselect 
ezgif com-video-to-gif (1)

### Toggle Campus is now dynamic and will move the map
ezgif com-video-to-gif (2)

### Click on map to deselect anything (Even searchBar context)
ezgif com-video-to-gif

### ⌚ 📈 App should be faster
The only components for which redux were not implemented are the SideMenu screens and Indoor.

## Test the branch
1. Checkout to `feature/redux-implementation` 
2. Do `npm install`
3. If step 2 still create crashes in the build: Try the following
- For Mac: `rm -rf node_modules` and redo `npm install`. 
- For Windows:  open file explorer of the project and delete the node_modules folder and redo `npm install`.
4. Do `npm start` or `expo start` 
5. test the new features and _**try to break them**_. 

## Small Note
PreviewDirections and Directions arrow back buttons may be hard to click now, @csbduzi will take of it. 🥇 
## Missing
Before you add comments on unit testing, I am aware. 
## Resolved Issue/Bug/Feature
Resolves #227 
Resolves #221 
Resolves #149 
Resolves #147

### CODE REVIEW

**Comment by bloulidi** [comment]
The marker is not placed in the right building when i choose EV building.
image

**Comment by csbduzi** [comment]
Any particular reason why Redux was not implemented for indoor and side menu?

**Comment by csbduzi** [comment]
A user might be tempted to press on the initials of a building, maybe try to have an onPress on the markers (characters) also, else they might think pressing on a building is not as responsive

File: screens/Map.js [hunk 1]
```diff
@@ -1,81 +1,82 @@
...
+                    <LocationMarker mapReference = {mapRef} />
                 </MapView>
-                <Search testID="searchBar" navigation={navigation} />
+                <Search testID="searchBar" 
+                navigation = {props.navigation} 
+                mapReference = {mapRef} 
+                />
                 <View style={styles.CurrentBuildingLocation}>
-                        <CurrentBuildingLocation />
+                        {/* <CurrentBuildingLocation /> */}
```
Comment (bloulidi) [inline screens/Map.js:77]: The current building location button should be uncommented.

File: screens/PreferenceMenu.js [hunk 2]
```diff
@@ -330,4 +377,4 @@ export const styles = StyleSheet.create({
     },
 });
 
-export default PreferenceMenu;
+// export default PreferenceMenu;
```
Comment (bloulidi) [inline screens/PreferenceMenu.js:380]: Unnused import

File: screens/PreviewDirections.js [hunk 3]
```diff
@@ -168,26 +173,28 @@ function PreviewDirections (props) {
...
                 const decodedPoints = decodedPolylinesAlgo(jsonResponse.routes[0].overview_polyline.points);
                 setDecodedPolylines(decodedPoints);
                 updateMapRegionToOverallPath(decodedPoints);
                 //Command Pattern
-                let filteredInstruction = getFilteredDetailedInstructions(jsonResponse.routes[0].legs[0], outdoorTransportType);
+                let filteredInstruction = getFilteredDetailedInstructions(jsonResponse.routes[0].legs[0], transportType);
                 filteredInstruction.generalRouteInfo.overviewPolyline = decodedPoints;
                 filteredInstruction.generalRouteInfo.isStartAddressClassRoom = fromCoordinates.isClassRoom ? fromCoordinates.isClassRoom : null;
                 filteredInstruction.generalRouteInfo.isEndAddressClassRoom = toCoordinates.isClassRoom ? toCoordinates.isClassRoom : null;
+                // console.log(filteredInstruction.steps);
```
Comment (bloulidi) [inline screens/PreviewDirections.js:197]: Do you need this ?

**Comment by csbduzi** [comment]
> The marker is not placed in the right building when i choose EV building.
> image

Yes, the coordinates for the EV building would have to be changed in the buildingData file

**Comment by csbduzi** [comment]
the onPress on the map to make the drop down list disappear is not a responsive 😥

**Comment by bloulidi** [comment]
Great job alain !! This is the cherry on top of the cake. 🍰 It feels very fluid and i love the new features. It makes the selection of the buildings a lot more responsive than before. MASHALLAH !!!

File: components/BottomMenu.js [hunk 4]
```diff
@@ -97,39 +75,33 @@ function BottomMenu(props) {
...
+        const unsubscribe = store.subscribe(() => {
+            setSelectedBuilding(store.getState().selectedBuildingName);
+            setDestination(store.getState().mainSearchBarDestination);
+            setPersonaType(store.getState().personaType);
+            setMobilityReduced(store.getState().mobilityReducedType);
+            setMethodTravel(store.getState().transportType);
+        });
+        return function cleanUp() {
+            unsubscribe();
+        }
```
Comment (csbduzi) [inline components/BottomMenu.js:93]: Nice!!

File: __tests__/unit/BuildingHighlight.test.js [hunk 5]
```diff
@@ -2,27 +2,46 @@ import React from "react";
...
   beforeEach(() => {
-    wrapper = shallow(<BuildingHighlight />);
+    wrapper = shallow(<BuildingHighlight {...props}/>);
   });
 
+  // component = renderer.create(
+  //   <Provider store={store}>
+  //     <BuildingHighlight />
+  //   </Provider>
+  // );
```
[the remark this answers is not in the document]
Comment (AlainJobs) [reply __tests__/unit/BuildingHighlight.test.js:29]: Probably not!

File: components/Search.js [hunk 6]
```diff
@@ -21,43 +36,36 @@ function fetchData () {
...
   }, []);
 
+  useEffect(() => {
+    updateSearchItem();
+  }, [searchItem]);
+
+  
   const goToMenu = () => {
-    AsyncStorage.setItem("sideMenu", "sideMenu");
+    AsyncStorage.setItem("sideMenu", "sideMenu"); //FIXME: Why?
```
[the remark this answers is not in the document]
Comment (AlainJobs) [reply components/Search.js:55]: No, this is mine, I added because I didn't understand the purpose of that statement

File: routes/drawer.js [hunk 7]
```diff
@@ -98,3 +99,9 @@ const Drawer = createDrawerNavigator({
 });
 
 export default createAppContainer(Drawer);
+
+// const mapStateToProps = state => ({
+//     navigation: state.navigation,
+//   })
+  
+//   export default connect(mapStateToProps)(allStacks)
```
[the remark this answers is not in the document]
Comment (AlainJobs) [reply routes/drawer.js:107]: will delete!

File: screens/Map.js (hunk 1 above)
Comment (AlainJobs) [reply screens/Map.js:77]: It creates warning that affects the performance of the app... Those warnings should be fix before

File: screens/PreferenceMenu.js (hunk 2 above)
Comment (AlainJobs) [reply screens/PreferenceMenu.js:380]: Good!

File: screens/PreviewDirections.js (hunk 3 above)
Comment (AlainJobs) [reply screens/PreviewDirections.js:197]: > the onPress on the map to make the drop down list disappear is not a responsive 😥
> 
> It works a times or sometime I feel like I have to press on specific spots on the map

It's legit the best we can do for the onPress event... Any other solution would have to use another event.

**Comment by AlainJobs** [comment]
> Any particular reason why Redux was not implemented for indoor and side menu?

Not really, you guys were working on it for a while and ultimately, you are not using asyncStorage calls in setIntervals as heavily as in BottomMenu and other components. I don't think it's necessary and we don't really have the time...

File: components/Search.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (csbduzi) [reply components/Search.js:55]: It's used for the_NearbyInterest_ component, to know from where you're reaching the component (either side-menu or the bottom menu).  The trick that I'm using is that as soon the user presses on the burger menu from _Map_, the value will be stored in the async storage to be retrieved by _NearbyInterest_

**Comment by AlainJobs** [comment]
> A user might be tempted to press on the initials of a building, maybe try to have an onPress on the markers (characters) also, else they might think pressing on a building is not as responsive
That would be another thing. It would just be a matter of adding the logic inside BuildingIdentification components like we did for BuildingHighlights. That would be nice if we have time

**Comment by AlainJobs** [comment]
> the onPress on the map to make the drop down list disappear is not a responsive 😥
> 
> It works a times or sometime I feel like I have to press on specific spots on the map

It's legit the best we can do for the onPress event... Any other solution would have to use another event.

**Comment by AlainJobs** [comment]
> I have no comments regarding the code. I tested the app & could not reproduce a bug (other than the marker mentioned above). Redux changes the game & the app is so much more smoother than have 30+ simultaneous calls every 1ms. Incredibly well done to resolve other issues & add little features here & there that enhance the user experience.
> 
> I will work on organizing unit testing after your PR is merged. For now, approved for me ✅

We move! 🤝

**Comment by AlainJobs** [comment]
> The marker is not placed in the right building when i choose EV building.
> image

Resolved!

File: components/Search.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (AlainJobs) [reply components/Search.js:55]: Ahh okay, it makes sense!

File: __tests__/unit/NearbyInterest.test.js [hunk 8]
```diff
@@ -4,24 +4,34 @@ import renderer from "react-test-renderer";
...
+
   let wrapper;
   const setState = jest.fn();
   const useStateSpy = jest.spyOn(React, "useState");
   useStateSpy.mockImplementation((init) => [init, setState]);
 
-
   beforeEach(() => {
     wrapper = shallow(<NearbyInterest />);
   });
```
Comment (Firassawan) [inline __tests__/unit/NearbyInterest.test.js:30]: Screen Shot 2020-04-18 at 1 18 02 PM

File: components/BottomMenu.js [hunk 9]
```diff
@@ -1,26 +1,24 @@
 /* eslint-disable no-unused-vars */
-import React, { useEffect } from "react";
+import React, { useLayoutEffect, useEffect } from "react";
```
Comment (Firassawan) [inline components/BottomMenu.js:2]: Screen Shot 2020-04-18 at 1 18 59 PM

File: components/Search.js [hunk 10]
```diff
@@ -1,10 +1,25 @@
-import React, { useEffect } from "react";
+import React, { useEffect, useState } from "react";
```
Comment (Firassawan) [inline components/Search.js:1]: Screen Shot 2020-04-18 at 1 19 40 PM

File: screens/Map.js [hunk 11]
```diff
@@ -1,81 +1,82 @@
...
-import React, { useEffect } from "react";
-import { StyleSheet, AsyncStorage } from "react-native";
+import React from "react";
+import { StyleSheet, Keyboard  } from "react-native";
 import MapView, { PROVIDER_GOOGLE } from "react-native-maps";
-import { BuildingHighlight } from "../components/BuildingHighlight";
+import BuildingHighlight  from "../components/BuildingHighlight";
 import { BuildingIdentification } from "../components/BuildingIdentification";
 import { BottomMenu } from "../components/BottomMenu";
 import { CurrentBuildingLocation } from "../components/CurrentBuildingLocation";
```
Comment (Firassawan) [inline screens/Map.js:8]: Screen Shot 2020-04-18 at 1 22 17 PM

**Comment by mohanadarafe** [comment]
I found a small bug. When searching Men's/Women's Washroom or Water Fountain (Indoor POI), the app responds with:

`null is not an object (evaluating 'searchItem.coordinates.latitude')`

File: screens/Map.js (hunk 11 above)
Comment (AlainJobs) [reply screens/Map.js:8]: I'm fixing this component, it will be there!

**Comment by AlainJobs** [comment]
> I found a small bug. When searching Men's/Women's Washroom or Water Fountain (Indoor POI), the app responds with:
> 
> `null is not an object (evaluating 'searchItem.coordinates.latitude')`

It makes sense, it should NOT be available in the mainSearchBar as I suggested last time.

File: __tests__/unit/NearbyInterest.test.js (hunk 8 above)
Comment (AlainJobs) [reply __tests__/unit/NearbyInterest.test.js:30]: I didn't touch that file. I think it would go on the refactor.

Comment (csbduzi) [reply __tests__/unit/NearbyInterest.test.js:30]: > I found a small bug. When searching Men's/Women's Washroom or Water Fountain (Indoor POI), the app responds with:
> 
> `null is not an object (evaluating 'searchItem.coordinates.latitude')`

It could be added to the DoubleSearch search bars manually instead, just like we did with current location and point of interest, and removed as soon as we pressed on the back button.

**Comment by csbduzi** [comment]
> I found a small bug. When searching Men's/Women's Washroom or Water Fountain (Indoor POI), the app responds with:
> 
> `null is not an object (evaluating 'searchItem.coordinates.latitude')`

It could be added to the DoubleSearch search bars manually instead, just like we did with current location and point of interest, and removed as soon as we pressed on the back button.

File: components/BottomMenu.js [hunk 12]
```diff
@@ -88,7 +66,7 @@ function BottomMenu(props) {
 
     const goToMoreDetails = () => {
         props.navigation.navigate("MoreDetails", {
-            name: selectedBuilding
+            name: store.getState().selectedBuildingName
```
[the remark this answers is not in the document]
Comment (AlainJobs) [reply components/BottomMenu.js:64]: > > I found a small bug. When searching Men's/Women's Washroom or Water Fountain (Indoor POI), the app responds with:
> > `null is not an object (evaluating 'searchItem.coordinates.latitude')`
> 
> It could be added to the DoubleSearch search bars manually instead, just like we did with current location and point of interest, and removed as soon as we pressed on the back button.

I fixed it differently, you would be able to see it in one of my latest commits

**Comment by AlainJobs** [comment]
> As soon the washrooom and the waterfountain bug will be fixed, I will approve the PR

It's fixed, but I'm doing more stuff. And I have Kenza changes to fix.

File: components/BottomMenu.js [hunk 13]
```diff
@@ -97,39 +75,33 @@ function BottomMenu(props) {
     };
 
     const goToNearby = () => {
-        AsyncStorage.setItem("sideMenu", "mapView");
+        AsyncStorage.setItem("sideMenu", "mapView"); //FIXME: WHY?
```
[the remark this answers is not in the document]
Comment (csbduzi) [reply components/BottomMenu.js]: Yes I had answered, in the updated code, its for the NearbyInterest Component, so that it can know from what component the user was coming from (ex: bottom menu or side menu)

File: screens/PreviewDirections.js [hunk 14]
```diff
@@ -227,29 +234,25 @@ function PreviewDirections (props) {
...
-    /**
-     * This method will fetch the value of the transport Type that is set in the asyncStorange.
-     * By default, the value is driving. 
-     */
-    const fetchTransportType = async () => {
-        let name = await AsyncStorage.getItem("thirdCategory");
-        if (name != null) {
-        setOutdoorTransportType(name);
+
+    useLayoutEffect (() => {
```
[the remark this answers is not in the document]
Comment (AlainJobs) [reply screens/PreviewDirections.js]: it is not! useLayoutEffect will allow unmounted components to change state without throwing unmounted warning. It uses more resource than UseEffect but do the same thing. You could see that useLayoutEffect is specially made to handle Layout Changes!

File: components/BottomMenu.js (hunk 12 above)
[the remark this answers is not in the document]
Comment (AlainJobs) [reply components/BottomMenu.js:64]: It's a feature of redux, I initialized one at redux/reducers/index.js. I could explain further in pm.

File: components/BottomMenu.js (hunk 13 above)
[the remark this answers is not in the document]
Comment (AlainJobs) [reply components/BottomMenu.js]: It was clarified!

File: components/BottomMenu.js [hunk 15]
```diff
@@ -97,39 +75,33 @@ function BottomMenu(props) {
...
-            case "transit":
-                return "Transit";
 
-            case "bicycling":
-                return "Bicycling";
-
-            default:
-                return "Driving";
+    const switchCampuses = (value) => {
+        setSwitchCampus(value);
```
[the remark this answers is not in the document]
Comment (AlainJobs) [reply components/BottomMenu.js:94]: YESSS!

File: components/Search.js [hunk 16]
```diff
@@ -21,43 +36,36 @@ function fetchData () {
...
+  }, [searchItem]);
+
+  
   const goToMenu = () => {
-    AsyncStorage.setItem("sideMenu", "sideMenu");
+    AsyncStorage.setItem("sideMenu", "sideMenu"); //FIXME: Why?
     props.navigation.openDrawer();
   };
 
+  const updateSearchItem = () => {
```
[the remark this answers is not in the document]
Comment (AlainJobs) [reply components/Search.js:60]: 👯‍♀️

File: screens/Map.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (AlainJobs) [reply screens/Map.js]: Fixed now!

Comment (bloulidi) [reply screens/Map.js]: What kind of warnings ? @AlainJobs

File: components/Search.js [hunk 17]
```diff
@@ -88,6 +96,9 @@ Search.propTypes = {
   navigation: PropTypes.object
 };
 
+export default connect(mapStateToProps, mapDispatchToProps)(Search);
```
[the remark this answers is not in the document]
Comment (AlainJobs) [reply components/Search.js:100]: Private message me!

**Comment by AlainJobs** [comment]
## Update
The currentBuildingLocation is implemented. I made some changes to it. It will update the bottom menu and highlight in blue the building your in. 
@mohanadarafe  is adding the CurrentLocationButton on Map.js
